"""
ECDAT — Offline Mode Engine
-----------------------------
Provides the offline sovereign-analysis capability for ECDAT.

Responsibilities:
  - Network safety guard: block external hosts in Offline Mode
  - Local TLS scanning: scan only loopback / private-network endpoints
  - Certificate file analysis: parse .pem / .crt / .cer files directly
  - Offline demo initialization: build offline_ecdat.db from local sources only
  - Offline inventory refresh: re-scan local TLS + local cert files + code

Design rules:
  - Never makes external network calls in Offline Mode
  - Never copies ecdat.db (live database) silently
  - Never silently falls back to Cached or Live mode
  - Results clearly labelled as local test / local demo where appropriate
  - The same MWQRS scoring pipeline is used as Live Mode (no fake scores)
"""

from __future__ import annotations

import ipaddress
import json
import socket
import ssl
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from cryptography import x509
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import rsa, ec, dsa

import ecdat_inventory as inv
import ecdat_scoring as score_eng
import ecdat_codescanner as code_eng
import ecdat_scanner as scanner_core


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

OFFLINE_DB = "offline_ecdat.db"

# The three local test servers created by generate_test_certs.py
LOCAL_TEST_SERVERS = [
    ("127.0.0.1", 8443),  # legacy-portal.internal — RSA-1024, TLSv1.0-1.2, short expiry
    ("127.0.0.1", 8444),  # api-gateway.internal   — RSA-3072, TLSv1.2-1.3, long expiry
    ("127.0.0.1", 8445),  # auth-service.internal  — RSA-2048, TLSv1.2-1.3, medium expiry
]

# Cert files generated by generate_test_certs.py (and any pre-existing project certs)
LOCAL_CERT_GLOB_PATTERNS = ["*_cert.pem", "*.crt", "*.cer"]

# Loopback ranges that are always allowed in Offline Mode
LOOPBACK_PREFIXES = ("127.", "::1")

# RFC 1918 private ranges — allowed for local-network scanning in Offline Mode
RFC1918_NETWORKS = [
    ipaddress.ip_network("10.0.0.0/8"),
    ipaddress.ip_network("172.16.0.0/12"),
    ipaddress.ip_network("192.168.0.0/16"),
]


# ---------------------------------------------------------------------------
# Network safety guard
# ---------------------------------------------------------------------------

def is_local_host(host: str) -> bool:
    """
    Returns True if ``host`` is a loopback address, 'localhost', or falls
    within an RFC 1918 private range.

    These hosts do NOT require internet access and are allowed in Offline Mode.
    """
    h = host.strip().lower()
    if h in ("localhost", "::1"):
        return True
    for prefix in LOOPBACK_PREFIXES:
        if h.startswith(prefix):
            return True
    # Try parsing as IP and checking RFC 1918
    try:
        addr = ipaddress.ip_address(h)
        for net in RFC1918_NETWORKS:
            if addr in net:
                return True
    except ValueError:
        pass  # not a bare IP — treat as external hostname
    return False


def is_blocked_in_offline_mode(host: str) -> bool:
    """
    Returns True if the host is NOT local and therefore must be blocked
    when Offline Mode is active.

    External hostnames (google.com, wikipedia.org, etc.) and public IPs
    always return True (= blocked).
    Local loopback and RFC 1918 addresses return False (= allowed).
    """
    return not is_local_host(host)


# ---------------------------------------------------------------------------
# Local TLS scanning (loopback / LAN only)
# ---------------------------------------------------------------------------

def scan_local_tls(
    targets: Optional[list] = None,
    timeout: float = 5.0,
) -> list[dict]:
    """
    Scans a list of (host, port) tuples — ONLY local/private addresses allowed.

    Parameters
    ----------
    targets : list of (host, port), defaults to LOCAL_TEST_SERVERS
    timeout : per-connection timeout in seconds

    Returns
    -------
    list of scan result dicts (same schema as ecdat_scanner.scan_host())

    Raises
    ------
    ValueError if any target host is external (safety guard).
    """
    if targets is None:
        targets = LOCAL_TEST_SERVERS

    results = []
    for host, port in targets:
        if is_blocked_in_offline_mode(host):
            raise ValueError(
                f"OFFLINE MODE SAFETY: '{host}' is an external host. "
                "Only loopback (127.x/localhost) and RFC 1918 addresses are "
                "allowed for local TLS scanning in Offline Mode."
            )
        res = scanner_core.scan_host(host, port, timeout=timeout)
        # Tag result as local scan for display purposes
        res["offline_source"] = "local_tls_scan"
        results.append(res)

    return results


# ---------------------------------------------------------------------------
# Certificate file analysis
# ---------------------------------------------------------------------------

def _get_key_info_from_public_key(public_key):
    """Return (key_type_str, key_size_bits) from a loaded public key object."""
    if isinstance(public_key, rsa.RSAPublicKey):
        return "RSA", public_key.key_size
    if isinstance(public_key, ec.EllipticCurvePublicKey):
        return f"ECC ({public_key.curve.name})", public_key.key_size
    if isinstance(public_key, dsa.DSAPublicKey):
        return "DSA", public_key.key_size
    return public_key.__class__.__name__, None


def analyze_cert_file(cert_path: Path) -> dict:
    """
    Parses a local X.509 certificate file (.pem / .crt / .cer) and returns
    a result dict in the same schema as ecdat_scanner.scan_host(), so it
    can be ingested directly via ecdat_inventory.ingest_scan_results().

    The host is set to the certificate's Common Name (or filename if absent).
    The port is set to 0 to indicate a file-based asset (not a live endpoint).
    tls_version is set to "N/A (cert file)" since no TLS handshake occurred.

    Supports both PEM and DER encoded certificates.
    """
    cert_path = Path(cert_path)
    result = {
        "host": cert_path.stem,
        "port": 0,
        "scanned_at": datetime.now(timezone.utc).isoformat(),
        "status": "unknown",
        "offline_source": "cert_file",
        "source_file": str(cert_path),
        "tls_version": "N/A (cert file)",
        "cipher_suite": None,
        "cipher_bits": None,
    }

    try:
        raw = cert_path.read_bytes()

        # Try PEM first, then DER
        cert = None
        if b"-----BEGIN CERTIFICATE-----" in raw:
            cert = x509.load_pem_x509_certificate(raw, default_backend())
        else:
            cert = x509.load_der_x509_certificate(raw, default_backend())

        key_type, key_size = _get_key_info_from_public_key(cert.public_key())

        sig_algo_raw = (
            getattr(cert.signature_algorithm_oid, "_name", None)
            or str(cert.signature_algorithm_oid)
        )
        if "ECC" in key_type and "RSA" in sig_algo_raw:
            hash_part = sig_algo_raw.split("With")[0] if "With" in sig_algo_raw else "sha256"
            sig_algo = f"ecdsa-with-{hash_part.lower()}"
        else:
            sig_algo = sig_algo_raw

        not_after = (
            cert.not_valid_after_utc
            if hasattr(cert, "not_valid_after_utc")
            else cert.not_valid_after
        )
        if not_after.tzinfo is None:
            not_after = not_after.replace(tzinfo=timezone.utc)
        days_to_expiry = (not_after - datetime.now(timezone.utc)).days

        subject = cert.subject.rfc4514_string()
        issuer = cert.issuer.rfc4514_string()

        # Use CN from subject as host name if available
        try:
            cn_attrs = cert.subject.get_attributes_for_oid(
                x509.oid.NameOID.COMMON_NAME
            )
            if cn_attrs:
                result["host"] = cn_attrs[0].value
        except Exception:
            pass

        result.update(
            {
                "status": "success",
                "cert_subject": subject,
                "cert_issuer": issuer,
                "cert_key_type": key_type,
                "cert_key_size_bits": key_size,
                "cert_signature_algorithm": sig_algo,
                "cert_not_after": not_after.isoformat(),
                "days_to_expiry": days_to_expiry,
            }
        )
        result["risk_flags"] = scanner_core.classify_risk(
            tls_version=None,
            key_type=key_type,
            key_size=key_size,
            sig_algo=sig_algo,
            days_to_expiry=days_to_expiry,
        )

    except FileNotFoundError:
        result["status"] = "error"
        result["error"] = f"Certificate file not found: {cert_path}"
    except (ValueError, Exception) as e:
        result["status"] = "error"
        result["error"] = f"Failed to parse certificate file: {e}"

    return result


def find_local_cert_files(search_dir: str = ".") -> list[Path]:
    """
    Finds certificate files in ``search_dir`` matching common extensions.
    Excludes key files and private-key material.
    """
    root = Path(search_dir)
    found = []
    for pattern in LOCAL_CERT_GLOB_PATTERNS:
        for p in root.glob(pattern):
            # Skip key files
            if "key" in p.name.lower():
                continue
            found.append(p)
    return sorted(set(found))


# ---------------------------------------------------------------------------
# Offline demo initialization
# ---------------------------------------------------------------------------

def initialize_offline_demo(db_path: str = OFFLINE_DB, search_dir: str = ".") -> dict:
    """
    Builds ``offline_ecdat.db`` from local sources only.

    Steps:
      1. Initialize schema (safe no-op if tables exist)
      2. Scan local TLS test servers (8443, 8444, 8445)
         - If server not running: record status='local_server_offline' stub
      3. Analyze local certificate files found in search_dir
      4. Seed offline demo services & dependencies (local-only mapping)
      5. Score all assets with MWQRS
      6. Return summary of what was done

    IMPORTANT: Does NOT copy ecdat.db. Does NOT make external network calls.
    Data labelled as 'Local Demo/Test Environment' where appropriate.
    """
    summary = {
        "db_path": db_path,
        "initialized_at": datetime.now(timezone.utc).isoformat(),
        "tls_scanned": 0,
        "tls_failed": 0,
        "cert_files_analyzed": 0,
        "cert_files_failed": 0,
        "assets_total": 0,
        "errors": [],
    }

    # 1. Initialize schema
    inv.init_db(db_path)

    # 2. Scan local TLS test servers
    tls_results = []
    for host, port in LOCAL_TEST_SERVERS:
        res = scanner_core.scan_host(host, port, timeout=5.0)
        res["offline_source"] = "local_tls_scan"
        tls_results.append(res)
        if res["status"] == "success":
            summary["tls_scanned"] += 1
        else:
            summary["tls_failed"] += 1
            summary["errors"].append(
                f"TLS {host}:{port} → {res.get('status')}: {res.get('error', '')}"
            )

    # Ingest TLS results into offline DB
    if tls_results:
        _ingest_results_direct(tls_results, db_path)

    # 3. Analyze local certificate files
    cert_files = find_local_cert_files(search_dir)
    cert_results = []
    for cp in cert_files:
        cr = analyze_cert_file(cp)
        cert_results.append(cr)
        if cr["status"] == "success":
            summary["cert_files_analyzed"] += 1
        else:
            summary["cert_files_failed"] += 1
            summary["errors"].append(
                f"Cert file {cp.name} → {cr.get('error', 'parse error')}"
            )

    # Ingest cert file results (only successful ones)
    successful_cert_results = [r for r in cert_results if r["status"] == "success"]
    if successful_cert_results:
        _ingest_results_direct(successful_cert_results, db_path)

    # 4. Seed offline demo services & dependencies (local-only)
    inv.seed_offline_demo_data(db_path)

    # 5. Score all assets
    scored = score_eng.score_all_assets(db_path)
    summary["assets_total"] = len(scored)

    return summary


# ---------------------------------------------------------------------------
# Offline inventory refresh
# ---------------------------------------------------------------------------

def refresh_offline_inventory(
    db_path: str = OFFLINE_DB,
    run_code_scan: bool = True,
    code_dir: str = ".",
    search_dir: str = ".",
) -> dict:
    """
    Re-scans all local sources and updates offline_ecdat.db.

    Steps:
      1. Scan local TLS test servers
      2. Analyze local certificate files
      3. Optionally run source code scanner
      4. Re-score all assets

    Returns a summary dict.
    """
    summary = {
        "db_path": db_path,
        "refreshed_at": datetime.now(timezone.utc).isoformat(),
        "tls_scanned": 0,
        "tls_failed": 0,
        "cert_files_analyzed": 0,
        "code_findings": 0,
        "assets_total": 0,
        "errors": [],
    }

    inv.init_db(db_path)

    # 1. Local TLS scan
    tls_results = []
    for host, port in LOCAL_TEST_SERVERS:
        res = scanner_core.scan_host(host, port, timeout=5.0)
        res["offline_source"] = "local_tls_scan"
        tls_results.append(res)
        if res["status"] == "success":
            summary["tls_scanned"] += 1
        else:
            summary["tls_failed"] += 1
            summary["errors"].append(
                f"TLS {host}:{port} → {res.get('status')}: {res.get('error', '')}"
            )
    if tls_results:
        _ingest_results_direct(tls_results, db_path)

    # 2. Local cert files
    cert_files = find_local_cert_files(search_dir)
    for cp in cert_files:
        cr = analyze_cert_file(cp)
        if cr["status"] == "success":
            _ingest_results_direct([cr], db_path)
            summary["cert_files_analyzed"] += 1
        else:
            summary["errors"].append(
                f"Cert file {cp.name} → {cr.get('error', 'parse error')}"
            )

    # 3. Source code scan
    if run_code_scan:
        try:
            findings = code_eng.scan_source_directory(code_dir, db_path)
            summary["code_findings"] = len(findings)
        except Exception as e:
            summary["errors"].append(f"Code scan error: {e}")

    # Re-seed services so new TLS results get linked
    inv.seed_offline_demo_data(db_path)

    # 4. Score
    scored = score_eng.score_all_assets(db_path)
    summary["assets_total"] = len(scored)

    return summary


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _ingest_results_direct(results: list[dict], db_path: str):
    """
    Ingests a list of scan result dicts directly into the offline database
    without going through a temporary JSON file.

    Uses the same INSERT … ON CONFLICT logic as ecdat_inventory.ingest_scan_results().
    """
    import sqlite3

    conn = inv.get_db_connection(db_path)
    cursor = conn.cursor()

    for item in results:
        host = item.get("host")
        port = item.get("port", 443)
        if not host:
            continue

        scanned_at = item.get("scanned_at")
        status = item.get("status", "unknown")
        tls_version = item.get("tls_version")
        cipher_suite = item.get("cipher_suite")
        cipher_bits = item.get("cipher_bits")
        cert_subject = item.get("cert_subject")
        cert_issuer = item.get("cert_issuer")
        cert_key_type = item.get("cert_key_type")
        cert_key_size_bits = item.get("cert_key_size_bits")
        cert_signature_algorithm = item.get("cert_signature_algorithm")
        cert_not_after = item.get("cert_not_after")
        days_to_expiry = item.get("days_to_expiry")
        risk_flags = item.get("risk_flags", [])

        if isinstance(risk_flags, list):
            risk_flags_str = json.dumps(risk_flags)
        else:
            risk_flags_str = str(risk_flags)

        # History record
        cursor.execute(
            """
            INSERT INTO crypto_assets_history (
                host, port, scanned_at, status, tls_version,
                cert_key_type, cert_key_size_bits, risk_flags
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                host, port, scanned_at, status, tls_version,
                cert_key_type, cert_key_size_bits, risk_flags_str,
            ),
        )

        # Main assets record (upsert)
        cursor.execute(
            """
            INSERT INTO crypto_assets (
                host, port, scanned_at, status, tls_version, cipher_suite, cipher_bits,
                cert_subject, cert_issuer, cert_key_type, cert_key_size_bits,
                cert_signature_algorithm, cert_not_after, days_to_expiry, risk_flags
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(host, port) DO UPDATE SET
                scanned_at=excluded.scanned_at,
                status=excluded.status,
                tls_version=excluded.tls_version,
                cipher_suite=excluded.cipher_suite,
                cipher_bits=excluded.cipher_bits,
                cert_subject=excluded.cert_subject,
                cert_issuer=excluded.cert_issuer,
                cert_key_type=excluded.cert_key_type,
                cert_key_size_bits=excluded.cert_key_size_bits,
                cert_signature_algorithm=excluded.cert_signature_algorithm,
                cert_not_after=excluded.cert_not_after,
                days_to_expiry=excluded.days_to_expiry,
                risk_flags=excluded.risk_flags;
            """,
            (
                host, port, scanned_at, status, tls_version, cipher_suite, cipher_bits,
                cert_subject, cert_issuer, cert_key_type, cert_key_size_bits,
                cert_signature_algorithm, cert_not_after, days_to_expiry, risk_flags_str,
            ),
        )

    conn.commit()
    conn.close()


# ---------------------------------------------------------------------------
# Quick self-test (run directly: python ecdat_offline.py)
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("=== ECDAT Offline Mode Engine - Self-Test ===\n")

    # Network safety guard
    external_hosts = ["google.com", "wikipedia.org", "8.8.8.8", "1.1.1.1"]
    local_hosts = ["127.0.0.1", "localhost", "192.168.1.1", "10.0.0.5"]

    print("Network safety guard:")
    for h in external_hosts:
        blocked = is_blocked_in_offline_mode(h)
        status = "BLOCKED [PASS]" if blocked else "ALLOWED [BUG]"
        print(f"  {h:25} -> {status}")
    for h in local_hosts:
        blocked = is_blocked_in_offline_mode(h)
        status = "ALLOWED [PASS]" if not blocked else "BLOCKED [BUG]"
        print(f"  {h:25} -> {status}")

    print("\nLocal cert file discovery:")
    certs = find_local_cert_files(".")
    if certs:
        for c in certs:
            print(f"  Found: {c.name}")
            result = analyze_cert_file(c)
            print(f"    Status: {result['status']}, Key: {result.get('cert_key_type')} {result.get('cert_key_size_bits')}b, Days: {result.get('days_to_expiry')}")
    else:
        print("  No cert files found in current directory.")

    print("\nInitializing offline demo (offline_ecdat.db)...")
    summary = initialize_offline_demo()
    print(f"  TLS scanned: {summary['tls_scanned']}, TLS failed: {summary['tls_failed']}")
    print(f"  Cert files analyzed: {summary['cert_files_analyzed']}")
    print(f"  Total assets in offline DB: {summary['assets_total']}")
    if summary["errors"]:
        print(f"  Errors ({len(summary['errors'])}):")
        for e in summary["errors"]:
            print(f"    - {e}")
    print("\nSelf-test complete.")

